import { readFile, stat } from "node:fs/promises";
import { extname, join, normalize } from "node:path";
import { createStore } from "./store.mjs";
import { analyzeMission } from "./intelligence.mjs";
import { DOMAINS, assertBoundary, getDomain } from "./domains.mjs";
import { publishProject } from "./github.mjs";
import { createAgent } from "./agent.mjs";
import { createRealtimeHub } from "./realtime.mjs";
import { createSandbox } from "./sandbox.mjs";
import { createIdentityProvider } from "./identity.mjs";
import { createRedisBus } from "./redis-bus.mjs";
import { createResearcher } from "./research.mjs";
import { createMetrics } from "./metrics.mjs";
import { createOrchestrator } from "./orchestrator.mjs";

const types={".html":"text/html",".css":"text/css",".js":"text/javascript",".svg":"image/svg+xml"};
const send=(res,status,body,headers={})=>{const data=typeof body==="string"?body:JSON.stringify(body);res.writeHead(status,{"content-type":"application/json; charset=utf-8","content-length":Buffer.byteLength(data),...headers});res.end(data);};
async function body(req){const chunks=[];let size=0;for await(const chunk of req){size+=chunk.length;if(size>1_000_000)throw Object.assign(new Error("Request body too large"),{status:413});chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString()||"{}");}catch{throw Object.assign(new Error("Invalid JSON"),{status:400});}}

export function createApp({root,databasePath=":memory:",agent:createAgentOverride,sandbox:createSandboxOverride,hub:createHubOverride,identity:createIdentityOverride}={}) {
  const hub=createHubOverride||createRealtimeHub({bus:createRedisBus()});
  const store=createStore(databasePath,{onEvent:(projectId,event)=>hub.publish(projectId,event)});
  const researcher=createResearcher();
  const agent=createAgentOverride||createAgent({researcher});
  const sandbox=createSandboxOverride||createSandbox();
  const identity=createIdentityOverride||createIdentityProvider();
  const orchestrator=createOrchestrator({agent,sandbox});
  const requestWindows=new Map();
  const metrics=createMetrics();
  function enforceRateLimit(req) { const key=req.socket.remoteAddress||"unknown",current=Date.now(),window=requestWindows.get(key)||{started:current,count:0};if(current-window.started>60_000){window.started=current;window.count=0;}window.count+=1;requestWindows.set(key,window);if(window.count>300)throw Object.assign(new Error("Too many requests"),{status:429,code:"RATE_LIMITED"}); }
  async function api(req,res,url){
    if(req.method==="GET"&&url.pathname==="/api/health")return send(res,200,{status:"ok",service:"silo",time:new Date().toISOString()});
    if(req.method==="GET"&&url.pathname==="/api/ready"){const missing=[];if(!agent.configured)missing.push("SILO_AI_BASE_URL/SILO_AI_API_KEY/SILO_AI_MODEL");if(process.env.SILO_ENV==="production"&&!process.env.SILO_WORKER_SECRET)missing.push("SILO_WORKER_SECRET");return missing.length?send(res,503,{status:"not_ready",missing}):send(res,200,{status:"ready",model:process.env.SILO_AI_MODEL||"injected",identity:identity.configured,realtime:Boolean(process.env.SILO_REDIS_URL)});}
    if(req.method==="GET"&&url.pathname==="/api/metrics"){const output=metrics.render();res.writeHead(200,{"content-type":"text/plain; version=0.0.4","content-length":Buffer.byteLength(output)});return res.end(output);}
    if(req.method==="GET"&&url.pathname==="/api/domains")return send(res,200,{domains:Object.entries(DOMAINS).map(([id,d])=>({id,label:d.label,roots:d.roots,system:d.system}))});
    if(url.pathname.startsWith("/api/internal/jobs/")){if(req.headers.authorization!==`Bearer ${process.env.SILO_WORKER_SECRET}`||!process.env.SILO_WORKER_SECRET)throw Object.assign(new Error("Worker authentication required"),{status:401});const input=await body(req);if(url.pathname==="/api/internal/jobs/lease"&&req.method==="POST")return send(res,200,{job:store.lease(input.workerId,input.types||["sandbox","agent"],input.leaseMs)});const internal=url.pathname.match(/^\/api\/internal\/jobs\/([^/]+)\/(complete|fail)$/);if(internal&&req.method==="POST")return send(res,200,internal[2]==="complete"?store.completeJob(internal[1],input.workerId,input.result):store.failJob(internal[1],input.workerId,input.error));return false;}
    if(req.method==="POST"&&url.pathname==="/api/projects") {const input=await body(req);const analysis=analyzeMission(input.mission);const created=store.createProject({name:input.name||analysis.projectType,mission:input.mission,analysis,ownerName:input.ownerName,ownerRole:input.ownerRole});return send(res,201,{project:store.project(created.id),credentials:created,analysis});}
    const match=url.pathname.match(/^\/api\/projects\/([^/]+)(?:\/(members|tasks|files|events|publish|stream|war-rooms|runs|stacks|jobs|builds))?(?:\/([^/]+))?(?:\/(apply|vote|resolve|swap))?$/); if(!match)return false;
    const [,projectId,resource,resourceId,action]=match;const project=store.project(projectId);if(!project)throw Object.assign(new Error("Project not found"),{status:404});
    const token=(req.headers.authorization||"").replace(/^Bearer\s+/i,"")||url.searchParams.get("access_token")||"";let member=store.authenticate(token,projectId);if(!member&&identity.configured){const principal=await identity.verify(token);member=principal&&store.memberBySubject(projectId,principal.subject);}if(!member)throw Object.assign(new Error("Valid project identity required"),{status:401});
    if(!resource&&req.method==="GET")return send(res,200,{project,members:store.members(projectId),files:store.files(projectId),stacks:store.stacks(projectId),connected:hub.size(projectId)});
    if(resource==="stream"&&req.method==="GET")return hub.connect(projectId,res);
    if(resource==="members"&&req.method==="POST"){const input=await body(req);getDomain(input.role);return send(res,201,{member:store.addMember(projectId,input)});}
    if(resource==="events"&&req.method==="GET")return send(res,200,{events:store.events(projectId)});
    if(resource==="jobs"&&resourceId&&req.method==="GET"){const job=store.job(resourceId,projectId);return job?send(res,200,{job}):send(res,404,{error:"Job not found"});}
    if(resource==="builds"&&resourceId&&req.method==="GET"){const build=store.build(resourceId,projectId);return build?send(res,200,{build}):send(res,404,{error:"Build not found"});}
    if(resource==="builds"&&!resourceId&&req.method==="POST"){if(!store.isOwner(projectId,member.user_id))throw Object.assign(new Error("Only the project owner can launch a whole-project build"),{status:403});const input=await body(req),build=store.createBuild(projectId,member.user_id,input.mission||project.mission,{mission:input.mission||project.mission,analysis:project.analysis,files:store.exportFiles(projectId),runTests:Boolean(input.runTests),runtime:input.runtime||"node"});if(input.synchronous===true){const leased=store.leaseById(build.jobId,`api-${process.pid}`);const result=await orchestrator.build(leased.payload);store.completeJob(leased.id,leased.lease_owner,result);return send(res,201,{build:store.build(build.id,projectId)});}return send(res,202,{build});}
    if(resource==="war-rooms"&&req.method==="GET"&&!resourceId)return send(res,200,{warRooms:store.warRooms(projectId)});
    if(resource==="war-rooms"&&resourceId&&(action==="vote"||action==="resolve")&&req.method==="POST"){const room=store.warRooms(projectId).find(item=>item.id===resourceId);if(!room)throw Object.assign(new Error("War Room not found"),{status:404});if(!room.domains.includes(member.role))throw Object.assign(new Error("Only specialists involved in this conflict can govern it"),{status:403});const input=await body(req);return action==="vote"?send(res,200,{warRoom:store.voteWarRoom(projectId,resourceId,member.user_id,input.proposal)}):send(res,200,{warRoom:store.resolveWarRoom(projectId,resourceId,input.resolution)});}
    if(resource==="stacks"&&resourceId&&action==="swap"&&req.method==="POST"){if(member.role!==resourceId)throw Object.assign(new Error(`Only the ${resourceId} specialist can swap this stack`),{status:403,code:"ROLE_VIOLATION"});const input=await body(req);if(!String(input.technology||"").trim())throw Object.assign(new Error("technology is required"),{status:400});const stack=store.swapStack(projectId,resourceId,input.technology);const generated=await agent.generate({domain:resourceId,prompt:`Migrate the ${resourceId} domain from ${stack.previous||"the current stack"} to ${stack.technology}. Preserve all public contracts and include rollback instructions.`,analysis:project.analysis,files:store.exportFiles(projectId).filter(file=>getDomain(resourceId).roots.some(root=>file.path.startsWith(root)))});assertBoundary(resourceId,generated.changes);const task=store.createTask(projectId,member.user_id,resourceId,`Stack migration to ${stack.technology}`,generated.changes,generated.contracts);return send(res,201,{stack,migrationTask:task});}
    if(resource==="runs"&&req.method==="POST"){const input=await body(req);if(input.synchronous===true){const id=store.createRun(projectId,member.user_id,input.runtime);const result=await sandbox.run({runtime:input.runtime,files:store.exportFiles(projectId),command:input.command});return send(res,200,{run:store.finishRun(projectId,id,result)});}return send(res,202,{job:store.enqueue(projectId,member.user_id,"sandbox",{runtime:input.runtime,command:input.command,files:store.exportFiles(projectId)})});}
    if(resource==="publish"&&req.method==="POST"){const input=await body(req);const result=await publishProject({owner:input.owner,repo:input.repo,branch:input.branch||"main",baseBranch:input.baseBranch,token:input.githubToken,files:store.exportFiles(projectId),message:input.message||`Publish ${project.name} from SILO`,pullRequest:input.pullRequest});store.event(projectId,"project.published",{owner:input.owner,repo:input.repo,branch:input.branch||"main",commit:result.commit,pullRequest:result.pullRequest});return send(res,200,result);}
    if(resource==="files"&&url.searchParams.get("research")&&req.method==="GET")return send(res,200,await researcher.search(url.searchParams.get("ecosystem")||"npm",url.searchParams.get("research")));
    if(resource==="files"&&req.method==="GET"){if(resourceId){const file=store.file(projectId,decodeURIComponent(resourceId));return file?send(res,200,{file}):send(res,404,{error:"File not found"});}return send(res,200,{files:store.files(projectId)});}
    if(resource==="tasks"&&req.method==="POST"&&!resourceId){const input=await body(req);const requested=input.domain||member.role;if(requested!==member.role)throw Object.assign(new Error(`Your assigned role is ${member.role}; you cannot run the ${requested} specialist`),{status:403,code:"ROLE_VIOLATION"});const domainFiles=store.exportFiles(projectId).filter(file=>getDomain(requested).roots.some(root=>file.path.startsWith(root)));if(input.async===true&&!input.changes)return send(res,202,{job:store.enqueue(projectId,member.user_id,"agent",{domain:requested,prompt:input.prompt,analysis:project.analysis,files:domainFiles})});const generated=input.changes?{changes:input.changes,contracts:input.contracts||[],source:"human"}:await agent.generate({domain:requested,prompt:input.prompt,analysis:project.analysis,files:domainFiles});assertBoundary(requested,generated.changes);const task=store.createTask(projectId,member.user_id,requested,input.prompt,generated.changes,generated.contracts);return send(res,201,{task,agent:{source:generated.source,model:generated.model||null,summary:generated.summary||null},domain:{id:requested,...getDomain(requested)}});}
    if(resource==="tasks"&&resourceId&&action==="apply"&&req.method==="POST"){const task=store.task(resourceId);if(!task||task.project_id!==projectId)throw Object.assign(new Error("Task not found"),{status:404});if(task.domain!==member.role)throw Object.assign(new Error("Only a member assigned to this domain can apply the task"),{status:403});assertBoundary(task.domain,task.changes);return send(res,200,{task:store.applyTask(resourceId)});}
    return false;
  }
  async function handler(req,res){const started=Date.now();res.once("finish",()=>{metrics.inc("silo_http_requests_total",{method:req.method,status:res.statusCode});metrics.inc("silo_http_duration_milliseconds_total",{},Date.now()-started);});try{res.setHeader("x-content-type-options","nosniff");res.setHeader("x-frame-options","DENY");res.setHeader("referrer-policy","no-referrer");res.setHeader("permissions-policy","camera=(), microphone=(), geolocation=()");res.setHeader("content-security-policy","default-src 'self'; style-src 'self' https://fonts.googleapis.com; font-src https://fonts.gstatic.com; connect-src 'self'; img-src 'self' data:");enforceRateLimit(req);const url=new URL(req.url,"http://localhost");if(url.pathname.startsWith("/api/")){const handled=await api(req,res,url);if(handled!==false)return;return send(res,404,{error:"API route not found"});}const relative=normalize(url.pathname==="/"?"index.html":url.pathname.slice(1));const file=join(root,relative);let info;try{info=await stat(file);}catch{throw Object.assign(new Error("Not found"),{status:404});}if(!file.startsWith(root)||!info.isFile())throw Object.assign(new Error("Not found"),{status:404});const data=await readFile(file);res.writeHead(200,{"content-type":`${types[extname(file)]||"text/plain"}; charset=utf-8`});res.end(data);}catch(error){send(res,error.status||500,{error:error.message,code:error.code||"REQUEST_FAILED",...(error.details||{})});}}
  return {handler,store,hub,agent,sandbox,identity,close:()=>{hub.close();store.close();}};
}
