import { DatabaseSync } from "node:sqlite";
import { mkdirSync } from "node:fs";
import { dirname } from "node:path";
import { randomUUID, createHash } from "node:crypto";
import { assertBoundary } from "./domains.mjs";

export function createStore(path, { onEvent = () => {} } = {}) {
  if (path !== ":memory:") mkdirSync(dirname(path), { recursive: true });
  const db = new DatabaseSync(path);
  db.exec(`PRAGMA journal_mode=WAL; PRAGMA foreign_keys=ON;
    CREATE TABLE IF NOT EXISTS projects (id TEXT PRIMARY KEY, name TEXT NOT NULL, mission TEXT NOT NULL, analysis TEXT NOT NULL, created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS members (project_id TEXT NOT NULL, user_id TEXT NOT NULL, name TEXT NOT NULL, role TEXT NOT NULL, token TEXT NOT NULL UNIQUE, PRIMARY KEY(project_id,user_id), FOREIGN KEY(project_id) REFERENCES projects(id));
    CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, user_id TEXT NOT NULL, domain TEXT NOT NULL, prompt TEXT NOT NULL, status TEXT NOT NULL, changes TEXT NOT NULL, created_at TEXT NOT NULL, FOREIGN KEY(project_id) REFERENCES projects(id));
    CREATE TABLE IF NOT EXISTS files (project_id TEXT NOT NULL, path TEXT NOT NULL, content TEXT NOT NULL, domain TEXT NOT NULL, version INTEGER NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(project_id,path));
    CREATE TABLE IF NOT EXISTS events (id INTEGER PRIMARY KEY AUTOINCREMENT, project_id TEXT NOT NULL, kind TEXT NOT NULL, payload TEXT NOT NULL, created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS contracts (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, task_id TEXT NOT NULL, domain TEXT NOT NULL, name TEXT NOT NULL, version TEXT NOT NULL, direction TEXT NOT NULL, created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS war_rooms (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, contract_name TEXT NOT NULL, domains TEXT NOT NULL, proposals TEXT NOT NULL, votes TEXT NOT NULL, status TEXT NOT NULL, resolution TEXT, created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS stacks (project_id TEXT NOT NULL, domain TEXT NOT NULL, technology TEXT NOT NULL, version INTEGER NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(project_id,domain));
    CREATE TABLE IF NOT EXISTS runs (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, user_id TEXT NOT NULL, runtime TEXT NOT NULL, status TEXT NOT NULL, result TEXT NOT NULL, created_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS identity_links (project_id TEXT NOT NULL, user_id TEXT NOT NULL, subject TEXT NOT NULL, PRIMARY KEY(project_id,subject));
    CREATE TABLE IF NOT EXISTS jobs (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, user_id TEXT NOT NULL, type TEXT NOT NULL, payload TEXT NOT NULL, status TEXT NOT NULL, attempts INTEGER NOT NULL, max_attempts INTEGER NOT NULL, available_at TEXT NOT NULL, lease_owner TEXT, lease_until TEXT, result TEXT, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS project_owners (project_id TEXT PRIMARY KEY, user_id TEXT NOT NULL);
    CREATE TABLE IF NOT EXISTS builds (id TEXT PRIMARY KEY, project_id TEXT NOT NULL, user_id TEXT NOT NULL, status TEXT NOT NULL, mission TEXT NOT NULL, job_id TEXT, result TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
  `);
  const now = () => new Date().toISOString();
  const json = value => JSON.stringify(value);
  const tokenHash = token => createHash("sha256").update(token).digest("hex");
  return {
    createProject({ name, mission, analysis, ownerName = "Project owner", ownerRole = "infrastructure" }) {
      const id = randomUUID(), userId = randomUUID(), token = randomUUID();
      db.prepare("INSERT INTO projects VALUES (?,?,?,?,?)").run(id, name, mission, json(analysis), now());
      db.prepare("INSERT INTO members VALUES (?,?,?,?,?)").run(id, userId, ownerName, ownerRole, tokenHash(token));
      db.prepare("INSERT OR IGNORE INTO project_owners VALUES (?,?)").run(id,userId);
      this.event(id, "project.created", { name, domains: 6 });
      return { id, userId, token };
    },
    project(id) { const row = db.prepare("SELECT * FROM projects WHERE id=?").get(id); return row && { ...row, analysis: JSON.parse(row.analysis) }; },
    authenticate(token, projectId) { if(!token)return undefined;const hash=tokenHash(token);const member=db.prepare("SELECT * FROM members WHERE (token=? OR token=?) AND project_id=?").get(hash,token,projectId);if(member&&member.token===token)db.prepare("UPDATE members SET token=? WHERE project_id=? AND user_id=?").run(hash,projectId,member.user_id);return member; },
    addMember(projectId, { name, role, subject }) { const userId = randomUUID(), token = randomUUID(); db.prepare("INSERT INTO members VALUES (?,?,?,?,?)").run(projectId, userId, name, role, tokenHash(token));if(subject)db.prepare("INSERT INTO identity_links VALUES (?,?,?)").run(projectId,userId,subject); this.event(projectId, "member.joined", { userId, name, role }); return { userId, token, role }; },
    memberBySubject(projectId,subject){return db.prepare("SELECT m.* FROM members m JOIN identity_links i ON i.project_id=m.project_id AND i.user_id=m.user_id WHERE i.project_id=? AND i.subject=?").get(projectId,subject);},
    isOwner(projectId,userId){return Boolean(db.prepare("SELECT 1 FROM project_owners WHERE project_id=? AND user_id=?").get(projectId,userId));},
    members(projectId) { return db.prepare("SELECT user_id,name,role FROM members WHERE project_id=?").all(projectId); },
    createTask(projectId, userId, domain, prompt, changes, contracts=[]) { const id=randomUUID(); db.prepare("INSERT INTO tasks VALUES (?,?,?,?,?,?,?,?)").run(id,projectId,userId,domain,prompt,"proposed",json(changes),now()); for(const contract of contracts) db.prepare("INSERT INTO contracts VALUES (?,?,?,?,?,?,?,?)").run(randomUUID(),projectId,id,domain,contract.name,contract.version||"1",contract.direction||"provides",now()); this.event(projectId,"task.proposed",{id,domain,prompt,files:changes.map(c=>c.path),contracts}); const rooms=this.detectConflicts(projectId,id,domain,contracts); return {id,status:"proposed",changes,contracts,warRooms:rooms}; },
    task(id) { const row=db.prepare("SELECT * FROM tasks WHERE id=?").get(id); return row && {...row,changes:JSON.parse(row.changes)}; },
    applyTask(id) { const task=this.task(id); if(!task) return; if(task.status!=="proposed") throw Object.assign(new Error("Only proposed tasks can be applied"),{status:409}); const write=db.prepare("INSERT INTO files VALUES (?,?,?,?,1,?) ON CONFLICT(project_id,path) DO UPDATE SET content=excluded.content,domain=excluded.domain,version=files.version+1,updated_at=excluded.updated_at"); db.exec("BEGIN"); try { for(const file of task.changes) write.run(task.project_id,file.path,file.content,task.domain,now()); db.prepare("UPDATE tasks SET status='applied' WHERE id=?").run(id); db.exec("COMMIT"); } catch(error){db.exec("ROLLBACK");throw error;} this.event(task.project_id,"task.applied",{id,domain:task.domain,files:task.changes.map(c=>c.path)}); return {...task,status:"applied"}; },
    files(projectId) { return db.prepare("SELECT path,domain,version,updated_at FROM files WHERE project_id=? ORDER BY path").all(projectId); },
    exportFiles(projectId) { return db.prepare("SELECT path,content FROM files WHERE project_id=? ORDER BY path").all(projectId); },
    file(projectId,path) { return db.prepare("SELECT * FROM files WHERE project_id=? AND path=?").get(projectId,path); },
    detectConflicts(projectId,taskId,domain,contracts){const rooms=[];for(const contract of contracts){const existing=db.prepare("SELECT * FROM contracts WHERE project_id=? AND name=? AND domain<>? ORDER BY created_at DESC LIMIT 1").get(projectId,contract.name,domain);if(existing&&existing.version!==(contract.version||"1")){const id=randomUUID(),domains=[existing.domain,domain];db.prepare("INSERT INTO war_rooms VALUES (?,?,?,?,?,?,?,NULL,?)").run(id,projectId,contract.name,json(domains),json([{taskId:existing.task_id,domain:existing.domain,version:existing.version},{taskId,domain,version:contract.version||"1"}]),json({}),"open",now());this.event(projectId,"war_room.opened",{id,contract:contract.name,domains});rooms.push(id);}}return rooms;},
    warRooms(projectId){return db.prepare("SELECT * FROM war_rooms WHERE project_id=? ORDER BY created_at DESC").all(projectId).map(x=>({...x,domains:JSON.parse(x.domains),proposals:JSON.parse(x.proposals),votes:JSON.parse(x.votes),resolution:x.resolution&&JSON.parse(x.resolution)}));},
    voteWarRoom(projectId,id,userId,proposal){const row=db.prepare("SELECT * FROM war_rooms WHERE id=? AND project_id=?").get(id,projectId);if(!row)throw Object.assign(new Error("War Room not found"),{status:404});if(row.status!=="open")throw Object.assign(new Error("War Room is already resolved"),{status:409});const votes=JSON.parse(row.votes);votes[userId]=proposal;db.prepare("UPDATE war_rooms SET votes=? WHERE id=?").run(json(votes),id);this.event(projectId,"war_room.voted",{id,userId,proposal});return {...row,votes};},
    resolveWarRoom(projectId,id,resolution){const row=db.prepare("SELECT * FROM war_rooms WHERE id=? AND project_id=?").get(id,projectId);if(!row)throw Object.assign(new Error("War Room not found"),{status:404});db.prepare("UPDATE war_rooms SET status='resolved',resolution=? WHERE id=?").run(json(resolution),id);this.event(projectId,"war_room.resolved",{id,resolution});return {id,status:"resolved",resolution};},
    swapStack(projectId,domain,technology){const current=db.prepare("SELECT * FROM stacks WHERE project_id=? AND domain=?").get(projectId,domain);const version=(current?.version||0)+1;db.prepare("INSERT INTO stacks VALUES (?,?,?,?,?) ON CONFLICT(project_id,domain) DO UPDATE SET technology=excluded.technology,version=excluded.version,updated_at=excluded.updated_at").run(projectId,domain,technology,version,now());this.event(projectId,"stack.swapped",{domain,from:current?.technology||null,to:technology,version});return {domain,technology,version,previous:current?.technology||null};},
    stacks(projectId){return db.prepare("SELECT domain,technology,version,updated_at FROM stacks WHERE project_id=?").all(projectId);},
    createRun(projectId,userId,runtime){const id=randomUUID();db.prepare("INSERT INTO runs VALUES (?,?,?,?,?,?,?)").run(id,projectId,userId,runtime,"running",json({}),now());this.event(projectId,"sandbox.started",{id,runtime});return id;},
    finishRun(projectId,id,result){db.prepare("UPDATE runs SET status=?,result=? WHERE id=? AND project_id=?").run(result.passed?"passed":"failed",json(result),id,projectId);this.event(projectId,"sandbox.finished",{id,passed:result.passed,exitCode:result.exitCode});return {id,...result};},
    enqueue(projectId,userId,type,payload,{maxAttempts=3,delayMs=0}={}){const id=randomUUID(),available=new Date(Date.now()+delayMs).toISOString();db.prepare("INSERT INTO jobs VALUES (?,?,?,?,?,'queued',0,?,?,NULL,NULL,NULL,NULL,?,?)").run(id,projectId,userId,type,json(payload),maxAttempts,available,now(),now());this.event(projectId,"job.queued",{id,type});return {id,status:"queued",type};},
    lease(workerId,types,leaseMs=120_000){db.exec("BEGIN IMMEDIATE");try{const placeholders=types.map(()=>"?").join(","),current=now();const job=db.prepare(`SELECT * FROM jobs WHERE ((status='queued' AND available_at<=?) OR (status='running' AND lease_until<=? AND attempts<max_attempts)) AND type IN (${placeholders}) ORDER BY created_at LIMIT 1`).get(current,current,...types);if(!job){db.exec("COMMIT");return null;}const until=new Date(Date.now()+leaseMs).toISOString();db.prepare("UPDATE jobs SET status='running',attempts=attempts+1,lease_owner=?,lease_until=?,updated_at=? WHERE id=?").run(workerId,until,current,job.id);db.exec("COMMIT");return {...job,payload:JSON.parse(job.payload),status:"running",lease_owner:workerId,lease_until:until,attempts:job.attempts+1};}catch(error){db.exec("ROLLBACK");throw error;}},
    leaseById(id,workerId,leaseMs=180_000){const job=db.prepare("SELECT * FROM jobs WHERE id=? AND status='queued'").get(id);if(!job)throw Object.assign(new Error("Queued build job not found"),{status:409});const until=new Date(Date.now()+leaseMs).toISOString();db.prepare("UPDATE jobs SET status='running',attempts=attempts+1,lease_owner=?,lease_until=?,updated_at=? WHERE id=? AND status='queued'").run(workerId,until,now(),id);return {...job,payload:JSON.parse(job.payload),status:"running",lease_owner:workerId,lease_until:until,attempts:job.attempts+1};},
    completeJob(id,workerId,result){const job=db.prepare("SELECT * FROM jobs WHERE id=? AND lease_owner=? AND status='running'").get(id,workerId);if(!job)throw Object.assign(new Error("Job lease not found"),{status:409});const payload=JSON.parse(job.payload);let resource;if(job.type==="agent"&&result.changes)resource=this.createTask(job.project_id,job.user_id,payload.domain,payload.prompt,result.changes,result.contracts||[]);if(job.type==="sandbox"){const runId=randomUUID();db.prepare("INSERT INTO runs VALUES (?,?,?,?,?,?,?)").run(runId,job.project_id,job.user_id,payload.runtime,result.passed?"passed":"failed",json(result),now());resource={runId};}if(job.type==="build"&&result.steps){const taskIds=[],warRooms=[];for(const step of result.steps){assertBoundary(step.domain,step.changes);const task=this.createTask(job.project_id,job.user_id,step.domain,step.prompt,step.changes,step.contracts||[]);if(task.warRooms.length)warRooms.push(...task.warRooms);else this.applyTask(task.id);taskIds.push(task.id);}const status=warRooms.length?"needs_review":result.status,buildResult={...result,status,files:undefined,warRooms};db.prepare("UPDATE builds SET status=?,result=?,updated_at=? WHERE job_id=?").run(status,json(buildResult),now(),id);resource={buildId:payload.buildId,taskIds,status,warRooms};result=buildResult;}const stored={...result,resource};db.prepare("UPDATE jobs SET status='completed',result=?,lease_owner=NULL,lease_until=NULL,updated_at=? WHERE id=?").run(json(stored),now(),id);this.event(job.project_id,"job.completed",{id,type:job.type,resource});return {id,status:"completed",resource};},
    failJob(id,workerId,error){const job=db.prepare("SELECT * FROM jobs WHERE id=? AND lease_owner=? AND status='running'").get(id,workerId);if(!job)throw Object.assign(new Error("Job lease not found"),{status:409});const retry=job.attempts<job.max_attempts,status=retry?"queued":"failed",available=new Date(Date.now()+Math.min(60_000,1000*2**job.attempts)).toISOString();db.prepare("UPDATE jobs SET status=?,error=?,available_at=?,lease_owner=NULL,lease_until=NULL,updated_at=? WHERE id=?").run(status,String(error).slice(0,4000),available,now(),id);this.event(job.project_id,retry?"job.retrying":"job.failed",{id,type:job.type,attempts:job.attempts});return {id,status};},
    job(id,projectId){const row=db.prepare("SELECT * FROM jobs WHERE id=? AND project_id=?").get(id,projectId);return row&&{...row,payload:JSON.parse(row.payload),result:row.result&&JSON.parse(row.result)};},
    createBuild(projectId,userId,mission,payload){const id=randomUUID();const job=this.enqueue(projectId,userId,"build",{...payload,buildId:id});db.prepare("INSERT INTO builds VALUES (?,?,?,'queued',?,?,NULL,?,?)").run(id,projectId,userId,mission,job.id,now(),now());this.event(projectId,"build.queued",{id,jobId:job.id});return {id,jobId:job.id,status:"queued"};},
    build(id,projectId){const row=db.prepare("SELECT * FROM builds WHERE id=? AND project_id=?").get(id,projectId);return row&&{...row,result:row.result&&JSON.parse(row.result)};},
    event(projectId,kind,payload){const result=db.prepare("INSERT INTO events(project_id,kind,payload,created_at) VALUES(?,?,?,?)").run(projectId,kind,json(payload),now());onEvent(projectId,{id:Number(result.lastInsertRowid),kind,payload,createdAt:now()});},
    events(projectId){return db.prepare("SELECT * FROM events WHERE project_id=? ORDER BY id DESC LIMIT 100").all(projectId).map(x=>({...x,payload:JSON.parse(x.payload)}));},
    close(){db.close();},
  };
}
